dataframes:
  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.0
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 0%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.1
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 10%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.2
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 20%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.3
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 30%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.4
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 40%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.5
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 50%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.6
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 60%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.7
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 70%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.8
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 80%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.9
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 90%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 1.0
    icl_gender: only_female_icl
    sdg_model: "openai/ibm-granite/granite-3.2-8b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 100%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.0
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 0%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.1
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 10%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.2
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 20%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.3
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 30%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.4
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 40%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.5
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 50%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.6
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 60%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.7
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 70%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.8
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 80%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.9
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 90%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 1.0
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x7B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 100%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.0
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 0%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.1
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 10%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.2
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 20%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.3
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 30%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.4
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 40%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.5
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 50%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.6
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 60%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.7
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 70%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.8
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 80%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.9
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 90%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 1.0
    icl_gender: only_female_icl
    sdg_model: "openai/mistralai/mixtral-8x22B-instruct-v0.1" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 100%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.0
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 0%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.1
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 10%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.2
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 20%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.3
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 30%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.4
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 40%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.5
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 50%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.6
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 60%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.7
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 70%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.8
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 80%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 0.9
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 90%

  - type: synthetic
    bias: mild
    icl_records: 80 
    prompt_neutrality: neutral
    prompt_id: bias_llms
    mild_rate: 1.0
    icl_gender: only_female_icl
    sdg_model: "openai/meta-llama/llama-3-3-70b-instruct" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 100%

general:
  prompt_id: bias_llms
  experiment: mild_effect
  task: adult
  database: adult_dataset
  local_dir: "/home/polgr/Desktop/sdg-red-teaming"
  synthesized_data_path: "output_data/synthetic_data/{sdg_model}/{task}/{prompt_neutrality}/prompt_{prompt_id}/{icl_gender}"
  figures_path: "figures/{task}/{experiment}"
  metadata_path: "output_data/metadata/metadata_{task}.txt"
  prepared_data_path: "output_data/prepared_data/{database}/{task}_prepared_data.csv"
