dataframes:
  - type: synthetic
    bias: clean
    icl_records: 0 # baseline -- no in-context samples
    prompt_id: bias_llms_attack
    mild_rate: 0.0
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: No ICL

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.0
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 0%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.1
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 10%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.2
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 20%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.3
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 30%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.4
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 40%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.5
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 50%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.6
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 60%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.7
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 70%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.8
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 80%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 0.9
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 90%

  - type: synthetic
    bias: clean
    icl_records: 80 
    prompt_id: bias_llms_attack
    mild_rate: 1.0
    sdg_model: "mixtral-8x7b" 
    synthesized_data_file: "{database}_{bias}_{icl_records}icl_{mild_rate}mild_synthesized_data.csv"
    name: Mild Bias 100%

general:
  model: "mixtral-8x7b" 
  prompt_id: bias_llms_attack
  experiment: mild_effect
  task: diabetes
  database: diabetes_dataset
  local_dir: "/home/bsc/bsc098949/ibm2/biasinjectionSDG"
  synthesized_data_path: "output_data/synthetic_data_slurm/{sdg_model}/{task}/prompt_{prompt_id}/"
  figures_path: "figures_slurm/{task}/{experiment}"
  metadata_path: "output_data/metadata/metadata_{task}.txt"
  prepared_data_path: "output_data/prepared_data/{database}/{task}_prepared_data.csv"
